INCENTIVE_KEYWORDS = [
    "happy hour",
    "discount",
    "deal",
    "deals",
    "special",
    "specials",
    "promo",
    "promotion",
    "offer",
    "offers",
    "coupon",
    "free",
    "no cover",
    "no charge",
    "complimentary",
    "half off",
    "half price",
    "% off",
    "save",
    "bogo",
    "2 for 1",
    "two for one",
    "early bird",
    "early entry",
    "matinee",
    "twilight",
    "admission",
    "cover charge",
    "ticket",
    "tickets",
    "wristband",
    "live music",
    "live band",
    "live entertainment",
    "open mic",
    "karaoke",
    "dj night",
    "concert",
    "group rate",
    "group pricing",
    "group discount",
    "party package",
    "birthday package",
    "private event",
    "unlimited",
    "tasting",
    "student",
    "senior",
    "military",
    "member",
    "loyalty",
    "monday",
    "tuesday",
    "wednesday",
    "thursday",
    "friday",
    "saturday",
    "sunday",
    "$",
]


LINK_KEYWORDS = [
    "happy-hour",
    "happyhour",
    "happy_hour",
    "specials",
    "special",
    "deals",
    "deal",
    "promo",
    "promotion",
    "offers",
    "offer",
    "discount",
    "coupons",
    "menu",
    "drinks",
    "drink",
    "bar",
    "events",
    "event",
    "live-music",
    "live-entertainment",
    "music",
    "shows",
    "tickets",
    "admission",
    "pricing",
    "packages",
    "groups",
    "party",
    "birthday",
]


NOISE_PHRASES = [
    "privacy policy",
    "terms of use",
    "cookie policy",
    "all rights reserved",
    "sign up",
    "subscribe",
    "follow us",
    "contact us",
    "get directions",
    "read more",
    "learn more",
    "view all",
    "book now",
    "order now",
]


MENU_FOOD_WORDS = [
    "burger",
    "pizza",
    "taco",
    "tacos",
    "salad",
    "soup",
    "steak",
    "chicken",
    "pasta",
    "sushi",
    "fries",
    "dessert",
    "appetizer",
    "entree",
    "gluten free",
    "vegetarian",
    "vegan",
]